spring:
    application:
        name: earthquake-tracker
    datasource:
        url: jdbc:mysql://localhost:3306/quakes?createDatabaseIfNotExist=true
        username: root
        password: L1ftOff$
    flyway:
        baseline-on-migrate: true
    constants:
        base_url: "https://earthquake.usgs.gov/fdsnws/event/1/"
        small_query_uri: "/query?format=geojson&starttime=2025-06-20&endtime=2026-06-20&alertlevel=green"
        large_query_uri: "/query?format=geojson&starttime=2024-06-20&endtime=2024-07-20"