spring:
    application:
        name: earthquake-tracker
    datasource:
        url: jdbc:mysql://localhost:3306/quakes?createDatabaseIfNotExist=true
        username: root
        password: L1ftOff$
    flyway:
        baseline-on-migrate: true